#!/usr/bin/env python3
from flask import Flask, render_template
import sqlite3
import requests

app = Flask(__name__)

@app.route("/")
def first():
	return render_template('index.html')

@app.route('/deets/<name>')
def deets(name):
	query = "select * from deets where name = '" + name + "'"
	con = sqlite3.connect('assets/accounts.db')
	con.row_factory = sqlite3.Row
	cur = con.cursor()
	cur.execute(query)
	row = cur.fetchone()
	cur.close()
	con.close()
	return render_template('deets.html', rowData=row, requests=name)


if __name__ == "__main__":
    app.run(host='0.0.0.0', port='8003', debug=True)

#
# Run in gunicorn like so:
# 	`gunicorn -w 2 app:app`
# where the first "app" is the name of the main py file and the second 
# "app" is the name of the variable in the flask definition line - i
# in this case, `app = Flask(__name__)`
#
